---
title: "Final project"
author: "Yiyun Sun"
date: "6/22/2020"
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
---
```{r}
library(car)
```


```{r}
FP <- read.csv("/Users/sunyiyun/Downloads/FP_dataset.csv", header=T)
new <- FP[, c(13:31)]
cor(new)
```


```{r}
fp <- FP[, c(8:9,11,13:15, 20, 27:29)]
summary(fp)
```


```{r}
summary(fp)
cor(new)
pairs(fp)
```



```{r}
full <- lm(ADM_RATE ~ ., data = fp[,-1])
summary(full)
```

```{r}
library(MASS)
stepAIC(lm(ADM_RATE ~ 1, data=fp), 
        scope=list(upper=lm(ADM_RATE ~ ., data = fp)), 
        direction = "both", k=log(nrow(fp)))
```















```{r}
model <- lm(formula = ADM_RATE ~ AVGFACSAL + COSTT4_A + PCT_BORN_US + 
    HBCU + PCT_BA, data = fp)
summary(model)
```


```{r}
par(mfrow=c(2,3))
plot(rstandard(model) ~ fp$HBCU, xlab="HBCU", ylab="St. Residuals")
plot(rstandard(model) ~ fp$COSTT4_A, xlab="COSST4_A", ylab="St. Residuals")
plot(rstandard(model) ~ fp$AVGFACSAL, xlab="AVGFACSAL", ylab="St. Residuals")
plot(rstandard(model) ~ fp$PCT_BA, xlab="BA", ylab="St. Residuals")
plot(rstandard(model) ~ fp$PCT_BORN_US, xlab="BORN_US", ylab="St. Residuals")
plot(rstandard(model) ~ fitted(full), xlab="fitted", ylab="St. Residuals")
```


```{r}
par(mfrow=c(2,2))
plot(model)
```

```{r}
mult <- lm(cbind(fp$ADM_RATE+0.01, fp$AVGFACSAL+0.01, fp$COSTT4_A+0.01,
                 fp$HBCU+0.01,  fp$PCT_BA+0.01, fp$PCT_BORN_US+0.01) ~ 1)
bc <- powerTransform(mult)
summary(bc)
```

```{r}
mod2 <- lm(I((ADM_RATE)^(1.55)) ~ I(sqrt(AVGFACSAL)) + I(sqrt(COSTT4_A))+ I(PCT_BORN_US^(-5.54)) + HBCU + I(PCT_BA^(9.80)), data = fp)
summary(mod2)
```

```{r}
par(mfrow=c(3,3))
plot(rstandard(mod2) ~ fitted(mod2), xlab="Fitted", ylab="Residuals")
plot(rstandard(mod2) ~ I(sqrt(fp$AVGFACSAL)), xlab="AVGFACSAL", ylab="Residuals")
plot(rstandard(mod2) ~ I(sqrt(fp$COSTT4_A)), xlab="COSSTT4_A", ylab="Residuals")
plot(rstandard(mod2) ~ I((fp$PCT_BORN_US)^(-5.54)), xlab="BORN", ylab="Residuals")
plot(rstandard(mod2) ~ fp$HBCU, xlab="HBCU", ylab="Residuals")
plot(rstandard(mod2) ~ I((fp$PCT_BA)^(9.80)), xlab="BA", ylab="Residuals")
qqnorm(rstandard(mod2))
abline(a = 0, b = 1)
```

```{r}
fp$ADM_RATE <- fp$ADM_RATE+0.01
boxCox(model)
```

```{r}
mod3<- lm(I(ADM_RATE^(1.5)) ~ AVGFACSAL + COSTT4_A + PCT_BORN_US + 
    HBCU + PCT_BA, data = fp)
summary(mod3)
```

```{r}
par(mfrow=c(3,3))
plot(rstandard(mod3) ~ fitted(mod3), xlab="Fitted", ylab="Residuals")
plot(rstandard(mod3) ~ fp$AVGFACSAL, xlab="AVGFACSAL", ylab="Residuals")
plot(rstandard(mod3) ~ fp$COSTT4_A, xlab="COSTT4_A", ylab="Residuals")
plot(rstandard(mod3) ~ fp$PCT_BORN_US, xlab="PCT_BORN_US", ylab="Residuals")
plot(rstandard(mod3) ~ fp$PCT_BA, xlab="PCT_BA", ylab="Residuals")
plot(rstandard(mod3) ~ fp$HBCU, xlab="HBCU", ylab="Residuals")
qqnorm(rstandard(mod3))
abline(a = 0, b = 1)
```


```{r}
h <- hatvalues(mod3)
threshold <- 2 * (length(mod3$coefficients)/nrow(fp))
w<- which(h > threshold)
h[w]


r <- rstandard(mod3)
w <- which(r > 2 | r < -2)
r[w]

D <- cooks.distance(mod3)
cutoff <- qf(0.5, 9, nrow(fp)-9, lower.tail=T)
which(D > cutoff)
fits <- dffits(mod3)
cutoff <- 2*sqrt(9/nrow(fp))
w <- which(abs(fits) > cutoff)
dfb <- dfbetas(full)
cutoff <- 2/sqrt(nrow(fp))
w <- which(abs(dfb[,9]) > cutoff)
D[w]
```














